name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secrets-scan:
    name: Secrets Scanning (Gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: security/.gitleaks.toml

  iac-scan:
    name: IaC Scanning (Checkov)
    runs-on: ubuntu-latest
    needs: secrets-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: false
          output_format: cli
          download_external_modules: false
          skip_check: CKV_AZURE_165,CKV_AZURE_237,CKV_AZURE_139,CKV_AZURE_164,CKV_AZURE_233,CKV_AZURE_166,CKV_AZURE_163,CKV_AZURE_167,CKV2_AZURE_32